name: Scraper

on:
  workflow_dispatch:
    inputs:
      days:
        type: number
        description: "Number of days to scrape"
        default: 1

concurrency:
  group: scheduled-data-scraper-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scrape-data:
    name: Scrape data
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DB_DATA_PATH: ${{ github.workspace }}/pglite-db
      FLAT_DATA_PATH: ${{ github.workspace }}/leaderboard-data

      LEADERBOARD_PATH: ${{ github.workspace }}/leaderboard
      LEADERBOARD_DATA_PATH: ${{ github.workspace }}/leaderboard-data
      SCRAPER_PATHS: ${{ github.workspace }}/leaderboard-github-scraper ${{ github.workspace }}/leaderboard-slack-scraper

      SCRAPE_DAYS: ${{ inputs.days }}

      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ORG: ohcnetwork

      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      SLACK_CHANNEL: ${{ vars.SLACK_EOD_CHANNEL }}

    steps:
      - name: üì• Checkout Leaderboard
        uses: actions/checkout@v5
        with:
          repository: ohcnetwork/leaderboard
          path: ${{ env.LEADERBOARD_PATH }}
          fetch-depth: 1

      - name: üì• Checkout Leaderboard Github Scraper
        uses: actions/checkout@v5
        with:
          repository: ohcnetwork/leaderboard-github-scraper
          path: ${{ github.workspace }}/leaderboard-github-scraper
          fetch-depth: 1

      - name: üì• Checkout Leaderboard Slack Scraper
        uses: actions/checkout@v5
        with:
          repository: ohcnetwork/leaderboard-slack-scraper
          path: ${{ github.workspace }}/leaderboard-slack-scraper
          fetch-depth: 1

      - name: üì• Checkout Leaderboard Data
        uses: actions/checkout@v5
        with:
          path: ${{ env.LEADERBOARD_DATA_PATH }}
          fetch-depth: 1
          persist-credentials: true

      - name: üì¶ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: üì¶ Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "24"
          cache: "pnpm"
          cache-dependency-path: |
            ${{ env.LEADERBOARD_PATH }}/pnpm-lock.yaml
            ${{ github.workspace }}/leaderboard-github-scraper/pnpm-lock.yaml
            ${{ github.workspace }}/leaderboard-slack-scraper/pnpm-lock.yaml

      - name: üì¶ Install Dependencies on all repositories
        run: |
          for repo in ${{ env.LEADERBOARD_PATH }} ${{ env.SCRAPER_PATHS }}; do
            cd $repo
            pnpm install
          done

      - name: üö¶ Prepare Database
        run: |
          for repo in ${{ env.LEADERBOARD_PATH }} ${{ env.SCRAPER_PATHS }}; do
            cd $repo
            pnpm db:prepare
            echo "‚úÖ DB prepare completed for $repo"
          done;

      - name: üì• Import from Flat Data to Database
        run: |
          for repo in ${{ env.LEADERBOARD_PATH }} ${{ env.SCRAPER_PATHS }}; do
            cd $repo
            pnpm db:import
            echo "‚úÖ DB import completed for $repo"
          done

      - name: üîç Scrape Data
        run: |
          for repo in ${{ env.SCRAPER_PATHS }}; do
            cd $repo
            pnpm db:scrape
            echo "‚úÖ Scraper completed for $repo"
          done

      - name: üì§ Export Data
        run: |
          cd /tmp/leaderboard
          pnpm db:export

          for repo in ${{ env.SCRAPER_PATHS }}; do
            cd $repo
            pnpm db:export
            echo "‚úÖ DB export completed for $repo"
          done

      - name: üì§ Commit and Push Changes to Leaderboard Data
        run: |
          cd /tmp/leaderboard-data
          git add .
          git commit -m "Update leaderboard data"
          git push
